### ISSUE TITLE
Error: Unknown function: 'default_content'

### ISSUE THREAD

**Issue by Haringstad** [voxpupuli/puppet-fail2ban#70] opened 2018-06-21 09:20 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby:  2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
- Distribution: Debian 9 (Stretch)
- Module version: 2.2.0
## How to reproduce (e.g Puppet code you use)
Including the class by itself produces this error.
## What are you seeing
Info: Using configured environment 'testing'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown function: 'default_content'. at /etc/puppetlabs/code/environments/testing/modules/fail2ban/manifests/init.pp:43:26 on node puppettest.backend.responseconcepts.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

## What behaviour did you expect instead
No error

**Comment by traylenator** [comment] 2018-06-21 09:53
Duplicate of #69 ?

**Closed** 2018-06-22 14:06 UTC
